version: '3.8'

services:
  django:
    build: .
    container_name: django_app
    restart: always
    command: gunicorn chocolate_house.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - db_volume:/app/db
    environment:
      - DEBUG=False  # Set to True for local development
      - DJANGO_SETTINGS_MODULE=chocolate_house.settings

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django

volumes:
  static_volume:
  db_volume:

